# This has been created by @lillieH1000

name: Build the YouTube Reborn deb

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@main

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout aricloverEXALT/sdks
        uses: actions/checkout@main
        with:
          repository: aricloverEXALT/sdks
          ref: master
          sparse-checkout: iPhoneOS17.5.sdk
          path: aricloverEXALT/sdks

      - name: Checkout aricloverEXALT/YouTubeHeader
        uses: actions/checkout@main
        with:
          repository: aricloverEXALT/YouTubeHeader
          ref: main
          path: YouTubeHeader

      - name: Build Package 
        run: |
          brew install make ldid 
          export THEOS=theos
          gmake clean package FINALPACKAGE=1
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
